In [1]:
import sys

In [2]:
sys.path.append(r'F:\PycharmProject\PycomCAD')

In [3]:
from pycomcad import *

In [4]:
acad=Autocad()

In [5]:
acad.CurrentFilename

'消力池收集池.dwg'

In [14]:
with open(r'E:\设计卷册\盘州响水施工场地截洪沟\鸿业道路文件\贵州响水施工场地截洪沟\贵州响水施工场地截洪沟\跌水方案二.bgz') as f:
    for i in f:
        print(i)
    

0 1400

25 1401

50 1405.484

75 1401.998

100 1394.431

125 1379.823

150 1372.139

175 1365.935

200 1358.949

225 1349.784

250 1341.717

275 1333.155

298.821 1330



In [15]:
a,b=[],[]

In [16]:
with open(r'E:\设计卷册\盘州响水施工场地截洪沟\鸿业道路文件\贵州响水施工场地截洪沟\贵州响水施工场地截洪沟\跌水方案二.bgz') as f:

    for i in f:
        p,q=i.split(' ')
        a.append(float(p))
        b.append(float(q))

In [17]:
a

[0.0,
 25.0,
 50.0,
 75.0,
 100.0,
 125.0,
 150.0,
 175.0,
 200.0,
 225.0,
 250.0,
 275.0,
 298.821]

In [18]:
b

[1400.0,
 1401.0,
 1405.484,
 1401.998,
 1394.431,
 1379.823,
 1372.139,
 1365.935,
 1358.949,
 1349.784,
 1341.717,
 1333.155,
 1330.0]

In [31]:
def sliceGroup(seq):
    a=[]
    count=len(seq)-1
    for i in range(count):
        j,*seq=seq
        a.append([j,seq[0]])
    return a

In [17]:
pnt=acad.GetPoint()

In [11]:
acad.AddTable(Apoint(*pnt),7,1,10,35)

<win32com.gen_py.AutoCAD 2007 Type Library.IAcadTable instance at 0x2509816844696>

In [25]:
s=acad.AddText('转点编号',Apoint(*pnt),3.5)

In [26]:
s.StyleName='WLZ'

In [28]:
s.Rotation=3.14/2

In [23]:
def addColumn(acad,pnt,stylename,wordHeight=3.5):
    x,y,z=pnt
    acad.AddTable(Apoint(*pnt),7,1,10,35)
    text=['转点编号/桩号','平面距离（m）','自然地面标高',
         '沟顶标高(m)','设计沟内底标高（m）','坡度（%）','沟道型式及尺寸']
    for t in text:
        word=acad.AddText(t,Apoint(x,y-10*(text.index(t)+1)),wordHeight)
        word.StyleName=stylename
        
    

In [24]:
addColumn(acad,pnt,'WLZ')

In [29]:
import numpy as np

In [31]:
np.loadtxt(r'C:\Users\QQ\Desktop\跌水.txt')

array([[   0.   , 1400.   ],
       [  25.   , 1401.   ],
       [  50.   , 1405.484],
       [  75.   , 1401.998],
       [ 100.   , 1394.431],
       [ 125.   , 1379.823],
       [ 150.   , 1372.139],
       [ 175.   , 1365.935],
       [ 182.297, 1364.236],
       [ 189.592, 1361.997],
       [ 196.888, 1360.007],
       [ 200.   , 1358.949],
       [ 225.   , 1349.784],
       [ 250.   , 1341.717],
       [ 261.763, 1337.304],
       [ 272.509, 1333.898],
       [ 283.256, 1330.895],
       [ 300.   , 1328.441],
       [ 325.   , 1328.   ],
       [ 348.19 , 1326.   ]])

In [138]:
test=np.loadtxt(r'C:\Users\QQ\Desktop\跌水.txt')

In [139]:
test[0]

array([   0., 1400.])

In [140]:
test.shape

(20, 2)

In [141]:
np.array([100,50])+test

array([[ 100.   , 1450.   ],
       [ 125.   , 1451.   ],
       [ 150.   , 1455.484],
       [ 175.   , 1451.998],
       [ 200.   , 1444.431],
       [ 225.   , 1429.823],
       [ 250.   , 1422.139],
       [ 275.   , 1415.935],
       [ 282.297, 1414.236],
       [ 289.592, 1411.997],
       [ 296.888, 1410.007],
       [ 300.   , 1408.949],
       [ 325.   , 1399.784],
       [ 350.   , 1391.717],
       [ 361.763, 1387.304],
       [ 372.509, 1383.898],
       [ 383.256, 1380.895],
       [ 400.   , 1378.441],
       [ 425.   , 1378.   ],
       [ 448.19 , 1376.   ]])

In [41]:
help(test)

Help on ndarray object:

class ndarray(builtins.object)
 |  ndarray(shape, dtype=float, buffer=None, offset=0,
 |          strides=None, order=None)
 |  
 |  An array object represents a multidimensional, homogeneous array
 |  of fixed-size items.  An associated data-type object describes the
 |  format of each element in the array (its byte-order, how many bytes it
 |  occupies in memory, whether it is an integer, a floating point number,
 |  or something else, etc.)
 |  
 |  Arrays should be constructed using `array`, `zeros` or `empty` (refer
 |  to the See Also section below).  The parameters given here refer to
 |  a low-level method (`ndarray(...)`) for instantiating an array.
 |  
 |  For more information, refer to the `numpy` module and examine the
 |  methods and attributes of an array.
 |  
 |  Parameters
 |  ----------
 |  (for the __new__ method; see Notes below)
 |  
 |  shape : tuple of ints
 |      Shape of created array.
 |  dtype : data-type, optional
 |      Any objec

In [44]:
test.flatten()

array([   0.   , 1400.   ,   25.   , 1401.   ,   50.   , 1405.484,
         75.   , 1401.998,  100.   , 1394.431,  125.   , 1379.823,
        150.   , 1372.139,  175.   , 1365.935,  182.297, 1364.236,
        189.592, 1361.997,  196.888, 1360.007,  200.   , 1358.949,
        225.   , 1349.784,  250.   , 1341.717,  261.763, 1337.304,
        272.509, 1333.898,  283.256, 1330.895,  300.   , 1328.441,
        325.   , 1328.   ,  348.19 , 1326.   ])

In [101]:
test1=np.array([pnt[0],pnt[1]])+test

In [102]:
test2=test1.flatten()[:10]

In [103]:
pnt

(463580.2344934315, 2807476.1493380517, 0.0)

In [60]:
test3=test2[:4]

In [59]:
acad.AddLwpline(*list(test2))

MemoryError: CreatingSafeArray

In [80]:
test3=tuple(test2)

In [81]:
test3

(463580.2344934315,
 2808876.1493380517,
 463605.2344934315,
 2808877.1493380517,
 463630.2344934315,
 2808881.633338052,
 463655.2344934315,
 2808878.147338052,
 463680.2344934315,
 2808870.5803380515)

In [83]:
test4=[i for i in test3]

In [100]:
test3

(463580.2344934315,
 2808876.1493380517,
 463605.2344934315,
 2808877.1493380517,
 463630.2344934315,
 2808881.633338052,
 463655.2344934315,
 2808878.147338052,
 463680.2344934315,
 2808870.5803380515)

In [88]:
acad.AddLwpline(*[463580.2344934315
                  ,2808876.1493380517
                  ,463605.2344934315
                  ,2808877.1493380517,])

<win32com.gen_py.AutoCAD 2007 Type Library.IAcadLWPolyline instance at 0x2510082570616>

In [93]:
acad.AddLwpline(*test3)

MemoryError: CreatingSafeArray

In [89]:
len(test4)

10

In [74]:
test2

array([ 463580.23449343, 2808876.14933805,  463605.23449343,
       2808877.14933805,  463630.23449343, 2808881.63333805,
        463655.23449343, 2808878.14733805,  463680.23449343,
       2808870.58033805])

In [98]:
test2=[1,2,3,4,5,6]

In [99]:
acad.AddLwpline(*test2)

<win32com.gen_py.AutoCAD 2007 Type Library.IAcadLWPolyline instance at 0x2510082541160>

In [104]:
test2

array([ 463580.23449343, 2808876.14933805,  463605.23449343,
       2808877.14933805,  463630.23449343, 2808881.63333805,
        463655.23449343, 2808878.14733805,  463680.23449343,
       2808870.58033805])

In [107]:
test3=test2-np.array([4000000])

In [109]:
test4=np.array([1,2,3,4,5,6])

In [112]:
test5=list(test4)

In [115]:
test5=[1,2,3,4,5,6]

In [116]:
acad.AddLwpline(*test5)

<win32com.gen_py.AutoCAD 2007 Type Library.IAcadLWPolyline instance at 0x2510082661904>

In [117]:
test

array([[   0.   , 1400.   ],
       [  25.   , 1401.   ],
       [  50.   , 1405.484],
       [  75.   , 1401.998],
       [ 100.   , 1394.431],
       [ 125.   , 1379.823],
       [ 150.   , 1372.139],
       [ 175.   , 1365.935],
       [ 182.297, 1364.236],
       [ 189.592, 1361.997],
       [ 196.888, 1360.007],
       [ 200.   , 1358.949],
       [ 225.   , 1349.784],
       [ 250.   , 1341.717],
       [ 261.763, 1337.304],
       [ 272.509, 1333.898],
       [ 283.256, 1330.895],
       [ 300.   , 1328.441],
       [ 325.   , 1328.   ],
       [ 348.19 , 1326.   ]])

In [120]:
test2.tolist()

[463580.2344934315,
 2808876.1493380517,
 463605.2344934315,
 2808877.1493380517,
 463630.2344934315,
 2808881.633338052,
 463655.2344934315,
 2808878.147338052,
 463680.2344934315,
 2808870.5803380515]

In [122]:
acad.AddLwpline(*test2.tolist())

<win32com.gen_py.AutoCAD 2007 Type Library.IAcadLWPolyline instance at 0x2510082659440>

In [143]:
pnt=acad.GetPoint()

In [144]:
test=test+np.array([pnt[0],pnt[1]])

In [145]:
test

array([[ 463783.79686592, 2808795.92379792],
       [ 463808.79686592, 2808796.92379792],
       [ 463833.79686592, 2808801.40779792],
       [ 463858.79686592, 2808797.92179792],
       [ 463883.79686592, 2808790.35479792],
       [ 463908.79686592, 2808775.74679792],
       [ 463933.79686592, 2808768.06279792],
       [ 463958.79686592, 2808761.85879792],
       [ 463966.09386592, 2808760.15979792],
       [ 463973.38886592, 2808757.92079792],
       [ 463980.68486592, 2808755.93079792],
       [ 463983.79686592, 2808754.87279792],
       [ 464008.79686592, 2808745.70779792],
       [ 464033.79686592, 2808737.64079792],
       [ 464045.55986592, 2808733.22779792],
       [ 464056.30586592, 2808729.82179792],
       [ 464067.05286592, 2808726.81879792],
       [ 464083.79686592, 2808724.36479792],
       [ 464108.79686592, 2808723.92379792],
       [ 464131.98686592, 2808721.92379792]])

In [146]:
acad.AddLwpline(*(test.flatten().tolist()))  #注意这里

<win32com.gen_py.AutoCAD 2007 Type Library.IAcadLWPolyline instance at 0x2510082500928>

In [150]:
test1=list(test.flatten())