ICD文件格式：

| 格式                   | 说明                                                         |
| ---------------------- | ------------------------------------------------------------ |
| StartZH                | 起点桩号                                                     |
| X,Y,Angle              | 起点坐标和方位角                                             |
| 1、Length,[EndAngle]   | 1:直线标示符，长度，后续单元起始方位角（可选）               |
| 2，R,Length,1/-1       | 2:圆曲线标示符，半径，长度，转向（1：右转；-1：左转）        |
| 3，A,EndR,1/-1         | 3:完整缓和曲线（R在无穷大~R0时）标识符，回旋参数，终点半径，转向（1：右转；-1：左转） |
| 4，A,StartR,1/-1       | 4:完整缓和曲线（R在R0~无穷大时）标识符，回旋参数，起点半径，转向（1：右转；-1：左转） |
| 5，A,StartR EndR,1/-1  | 5：不完整缓和曲线（R在(R大-R 小)时）标识符，回旋参数起点半径，终点半径，转向（1：右转；-1：左转） |
| 6，A ,StartR EndR,1/-1 | 6：不完整缓和曲线（R在(R大-R 小)时）标识符，回旋参数起点半径，终点半径，转向（1：右转；-1：左转） |
| 0 0 0                  | 结束符                                                       |



In [1]:
import numpy as np

In [2]:
import math

In [3]:
import sys

In [4]:
sys.path.append(r'E:\programming\pycomcad\PycomCAD')

In [5]:
from pycomcad import *

In [51]:
test=np.loadtxt(r'bgs.txt');test

array([[   0.   , 1396.93 ,    0.   ],
       [  96.089, 1394.716,    0.   ],
       [ 125.   , 1377.823,    0.   ],
       [ 200.   , 1356.949,    0.   ],
       [ 283.326, 1328.885,    0.   ],
       [ 298.821, 1327.56 ,    0.   ]])

In [54]:
test.shape[-1]==3

True

In [6]:
bgs=np.loadtxt(r'bgs.txt');bgs

array([[   0.   , 1396.93 ,    0.   ],
       [  96.089, 1394.716,    0.   ],
       [ 125.   , 1377.823,    0.   ],
       [ 200.   , 1356.949,    0.   ],
       [ 283.326, 1328.885,    0.   ],
       [ 298.821, 1327.56 ,    0.   ]])

In [7]:
bgs=bgs[:,:2];bgs

array([[   0.   , 1396.93 ],
       [  96.089, 1394.716],
       [ 125.   , 1377.823],
       [ 200.   , 1356.949],
       [ 283.326, 1328.885],
       [ 298.821, 1327.56 ]])

In [8]:
bgz=np.loadtxt(r'bgz.txt')

In [9]:
bgz

array([[   0.   , 1400.   ],
       [  25.   , 1401.   ],
       [  50.   , 1405.484],
       [  75.   , 1401.998],
       [ 100.   , 1394.431],
       [ 125.   , 1379.823],
       [ 150.   , 1372.139],
       [ 175.   , 1365.935],
       [ 200.   , 1358.949],
       [ 225.   , 1349.784],
       [ 250.   , 1341.717],
       [ 275.   , 1333.155],
       [ 298.821, 1330.   ]])

In [10]:
acad=Autocad()

In [11]:
acad.IsEarlyBind

True

In [12]:
# acad.TurnOnEarlyBind()

In [13]:
pnt=acad.GetPoint()

In [14]:
def addColumn(acad,pnt,stylename,wordHeight=3.5):
    x,y,z=pnt
    acad.AddTable(Apoint(*pnt),7,1,11,35)
    text=['转点编号/桩号','平面距离（m）','自然地面标高',
         '沟顶标高(m)','设计沟内底标高（m）','坡度（%）','沟道型式及尺寸']
    for t in text:
        word=acad.AddText(t,Apoint(x,y-11*(text.index(t)+1)),wordHeight)
        word.StyleName=stylename

In [15]:
addColumn(acad,pnt,'WLZ')

In [16]:
bgs.min(axis=0)

array([   0.  , 1327.56])

In [62]:
bgz.min(axis=0)

array([   0., 1330.])

In [17]:
bgsL=np.array([pnt[0]+35,pnt[1]])+(bgs-bgs.min(axis=0))*np.array([5,5])

In [18]:
bgsL

array([[ 481669.48201716, 2808287.9069898 ],
       [ 482149.92701716, 2808276.8369898 ],
       [ 482294.48201716, 2808192.3719898 ],
       [ 482669.48201716, 2808088.0019898 ],
       [ 483086.11201716, 2807947.6819898 ],
       [ 483163.58701716, 2807941.0569898 ]])

In [19]:
bgsL.flatten().tolist()

[481669.48201715806,
 2808287.906989805,
 482149.9270171581,
 2808276.8369898046,
 482294.48201715806,
 2808192.371989805,
 482669.48201715806,
 2808088.0019898047,
 483086.11201715807,
 2807947.681989805,
 483163.58701715805,
 2807941.056989805]

In [20]:
acad.AddLwpline(*bgsL.flatten().tolist())

<win32com.gen_py.AutoCAD 2014 Type Library.IAcadLWPolyline instance at 0x2867665915016>

In [21]:
bgzL=np.array([pnt[0]+35,pnt[1]])+(bgz-bgs.min(axis=0))*np.array([5,5])

In [22]:
bgz

array([[   0.   , 1400.   ],
       [  25.   , 1401.   ],
       [  50.   , 1405.484],
       [  75.   , 1401.998],
       [ 100.   , 1394.431],
       [ 125.   , 1379.823],
       [ 150.   , 1372.139],
       [ 175.   , 1365.935],
       [ 200.   , 1358.949],
       [ 225.   , 1349.784],
       [ 250.   , 1341.717],
       [ 275.   , 1333.155],
       [ 298.821, 1330.   ]])

In [23]:
acad.AddLwpline(*bgzL.flatten().tolist())

<win32com.gen_py.AutoCAD 2014 Type Library.IAcadLWPolyline instance at 0x2867665914512>

In [24]:
acad.AddCircle(Apoint(*pnt),10)

<win32com.gen_py.AutoCAD 2014 Type Library.IAcadCircle instance at 0x2867668658048>

In [25]:
pnt

(481634.48201715806, 2807941.056989805, 0.0)

In [26]:
LH=acad.AddLine(Apoint(pnt[0]+35,pnt[1]),Apoint(pnt[0]+35+bgz.max(axis=0)[0]*5,pnt[1]))

In [27]:
for i in range(7):
    LH.Offset(-11*(i+1))

In [28]:
ZH=np.loadtxt(r'pm.txt',delimiter=',');ZH

array([[  1.      , 182.296587],
       [  2.      ,  14.591133],
       [  1.      ,   0.809412],
       [  2.      ,  19.812314],
       [  1.      ,  16.379723]])

In [29]:
zh1=ZH[:,1];zh1

array([182.296587,  14.591133,   0.809412,  19.812314,  16.379723])

In [30]:
zh1=np.cumsum(zh1);zh1

array([182.296587, 196.88772 , 197.697132, 217.509446, 233.889169])

In [31]:
zh1L=acad.AddLine(Apoint(pnt[0]+35,pnt[1]),Apoint(pnt[0]+35,pnt[1]-77))

In [32]:
for i in zh1:
    zh1L.Offset(i*5)

In [33]:
bgz

array([[   0.   , 1400.   ],
       [  25.   , 1401.   ],
       [  50.   , 1405.484],
       [  75.   , 1401.998],
       [ 100.   , 1394.431],
       [ 125.   , 1379.823],
       [ 150.   , 1372.139],
       [ 175.   , 1365.935],
       [ 200.   , 1358.949],
       [ 225.   , 1349.784],
       [ 250.   , 1341.717],
       [ 275.   , 1333.155],
       [ 298.821, 1330.   ]])

In [34]:
bgs

array([[   0.   , 1396.93 ],
       [  96.089, 1394.716],
       [ 125.   , 1377.823],
       [ 200.   , 1356.949],
       [ 283.326, 1328.885],
       [ 298.821, 1327.56 ]])

In [35]:
import pandas as pd

In [63]:
a=[1,2,3];b=[3,4]

In [36]:
distance=bgs[:,0].tolist()+zh1.tolist()+bgz[:,0].tolist()

In [37]:
distance

[0.0,
 96.089,
 125.0,
 200.0,
 283.326,
 298.821,
 182.296587,
 196.88772,
 197.697132,
 217.50944600000003,
 233.88916900000004,
 0.0,
 25.0,
 50.0,
 75.0,
 100.0,
 125.0,
 150.0,
 175.0,
 200.0,
 225.0,
 250.0,
 275.0,
 298.821]

In [38]:
np.interp?

In [39]:
df=pd.DataFrame({'Distance':distance,'BGZ':np.interp(distance,bgz[:,0],bgz[:,1]),'BGS':np.interp(distance,bgs[:,0],bgs[:,1])})

In [40]:
df

Distance          BGZ          BGS
0     0.000000  1400.000000  1396.930000
1    96.089000  1395.614781  1394.716000
2   125.000000  1379.823000  1377.823000
3   200.000000  1358.949000  1356.949000
4   283.326000  1332.052253  1328.885000
5   298.821000  1330.000000  1327.560000
6   182.296587  1363.896042  1361.876214
7   196.887720  1359.818696  1357.815210
8   197.697132  1359.592513  1357.589934
9   217.509446  1352.530037  1351.051860
10  233.889169  1346.915643  1345.535208
11    0.000000  1400.000000  1396.930000
12   25.000000  1401.000000  1396.353972
13   50.000000  1405.484000  1395.777943
14   75.000000  1401.998000  1395.201915
15  100.000000  1394.431000  1392.430762
16  125.000000  1379.823000  1377.823000
17  150.000000  1372.139000  1370.865000
18  175.000000  1365.935000  1363.907000
19  200.000000  1358.949000  1356.949000
20  225.000000  1349.784000  1348.529059
21  250.000000  1341.717000  1340.109118
22  275.000000  1333.155000  1331.689177
23  298.821000  1330.000000  1327.560000

In [41]:
df.index.argmax()

23

In [42]:
x,y,z=pnt

In [43]:
acad.AddText?

In [44]:
for i in range(df.index.argmax()+1):
    distance,BGZ,BGS=df.iloc[i].values
    zh1L.Offset(distance*5)
    zhuanghao=acad.AddText('+'+str(round(distance,2)),Apoint(x+35+distance*5,y-5.5),2.5)
    ziranbiaogao=acad.AddText(str(round(BGZ,2)),Apoint(x+35+distance*5,y-35),2.5)
    shejibiaogao=acad.AddText(str(round(BGS,2)),Apoint(x+35+distance*5,y-55),2.5)
    zhuanghao.Rotation=math.radians(90)
    ziranbiaogao.Rotation=math.radians(90)
    shejibiaogao.Rotation=math.radians(90)
    

In [45]:
def drawElevationRuler(acad,x,y,scale,maxH,minH,wordHeight,intern=1):
    """
    x,y:标尺最低点的坐标
    绘制标高尺
    scale:标尺比例
    intern:m,标尺间隔
    maxH:最高,m
    """
    n=math.floor((maxH-minH)/intern)+1
    acad.AddLwpline(x,y,x+1,y,x+1,y+n*intern*1000/scale,x,y+n*intern*1000/scale,x,y)
    texts=[str(minH+intern*i) for i in range(n)]
    for i in range(n):
        textPnt=Apoint(x-10,y+i*intern*1000/scale)  #字体距离标尺左边距离
        text=acad.AddText(texts[i],textPnt,wordHeight)
        ys=y+i*intern*1000/scale
        ye=y+(i+1)*intern*1000/scale
        if i%2==0:
            xx=x+0.75
        else:
            xx=x+0.25
        pl=acad.AddLwpline(xx,ys,xx,ye)
        pl.ConstantWidth=0.5

In [46]:
pnt

(481634.48201715806, 2807941.056989805, 0.0)

In [47]:
bgs

array([[   0.   , 1396.93 ],
       [  96.089, 1394.716],
       [ 125.   , 1377.823],
       [ 200.   , 1356.949],
       [ 283.326, 1328.885],
       [ 298.821, 1327.56 ]])

In [48]:
ymin=bgs.min(axis=0)[1];ymin

1327.56

In [49]:
ymax=np.vstack((bgs,bgz)).max(axis=0)[1];ymax

1405.484

In [50]:
drawElevationRuler(acad,x-5,y-0.56*5,200,int(ymax)+1,int(ymin),2.5)